### ISSUE TITLE
libnxml release 0.18.4 not tagged

### ISSUE THREAD

**Issue by hosiet** [bakulf/libnxml#14]
As I see from https://github.com/bakulf/libnxml/commit/887a515b83feeca309c4740822e676812fff5df9 a new version 0.18.4 was generated. However, it does not show up at https://github.com/bakulf/libnxml/releases or https://github.com/bakulf/libnxml/tags . Perhaps a new git tag or release is needed.

**Comment by dirkmueller** [comment]
ping.. is there any way to push the tag or create a Git Hub release?

**Comment by fcolista** [comment]
Ping here too....can you please create a release o tag it?
